import type { Listing, AgentProfile, BuyerProfile, ContactLog } from "./types"

// Mock Agents - Added whatsapp field
export const mockAgents: AgentProfile[] = [
  {
    id: "agent-1",
    email: "arben.hoxha@realestate.al",
    name: "Arben Hoxha",
    role: "agent",
    phone: "+355 69 123 4567",
    whatsapp: "+355691234567",
    avatar: "/professional-man-suit.png",
    verificationStatus: "approved",
    licenseNumber: "AL-BRK-2024-001",
    agency: "Tirana Business Brokers",
    bio: "Over 15 years of experience in business acquisitions across Albania. Specializing in hospitality and retail sectors.",
    listingsCount: 12,
    dealsCompleted: 45,
    verifiedAt: new Date("2024-01-15"),
    createdAt: new Date("2023-06-01"),
    creditBalance: 50,
  },
  {
    id: "agent-2",
    email: "elena.koci@brokers.al",
    name: "Elena Koci",
    role: "agent",
    phone: "+355 69 987 6543",
    whatsapp: "+355699876543",
    avatar: "/professional-woman-businesswoman.jpg",
    verificationStatus: "approved",
    licenseNumber: "AL-BRK-2024-002",
    agency: "Premium Business Sales",
    bio: "Expert in technology and service-based business transactions. Fluent in English, Italian, and Albanian.",
    listingsCount: 8,
    dealsCompleted: 28,
    verifiedAt: new Date("2024-02-20"),
    createdAt: new Date("2023-08-15"),
    creditBalance: 25,
  },
]

// Mock Buyers - Simplified, removed verification fields
export const mockBuyers: BuyerProfile[] = [
  {
    id: "buyer-1",
    email: "investor@example.com",
    name: "Marco Rossi",
    role: "buyer",
    phone: "+39 333 123 4567",
    companyName: "Rossi Investments Ltd.",
    savedListings: ["listing-1", "listing-3"],
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "buyer-2",
    email: "buyer@example.com",
    name: "Sarah Johnson",
    role: "buyer",
    phone: "+1 555 123 4567",
    companyName: "SJ Holdings",
    savedListings: [],
    createdAt: new Date("2024-11-01"),
  },
  {
    id: "buyer-3",
    email: "demo@example.com",
    name: "Demo User",
    role: "buyer",
    savedListings: ["listing-2"],
    createdAt: new Date("2024-11-20"),
  },
]

// Mock Listings
export const mockListings: Listing[] = [
  {
    id: "listing-1",
    agentId: "agent-1",
    agent: mockAgents[0],
    publicTitle: "High-End Italian Restaurant",
    publicDescription:
      "Award-winning Italian restaurant in prime location. Established clientele with consistent revenue growth over 5 years. Full kitchen equipment included. Excellent reputation and online reviews.",
    category: "restaurant",
    address: {
      real: {
        street: "Rruga e Durresit, Nr 25",
        city: "Tirana",
        country: "Albania",
        coordinates: { lat: 41.3275, lng: 19.8187 },
      },
      public: {
        area: "Blloku Area",
        city: "Tirana",
        country: "Albania",
        radiusKm: 1,
      },
    },
    realBusinessName: "Trattoria Bella Napoli",
    realDescription: "Family-owned since 2015. Located on the main pedestrian street.",
    askingPrice: 350000,
    annualRevenue: 480000,
    monthlyProfit: 12000,
    roi: 41,
    employeeCount: 12,
    yearsInOperation: 8,
    leaseTermsMonths: 60,
    images: [
      "/elegant-italian-restaurant.png",
      "/restaurant-kitchen-professional.jpg",
      "/outdoor-restaurant-terrace.jpg",
    ],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-11-15"),
    viewCount: 234,
    inquiryCount: 12,
    promotionTier: "premium",
  },
  {
    id: "listing-2",
    agentId: "agent-1",
    agent: mockAgents[0],
    publicTitle: "Profitable Cocktail Bar",
    publicDescription:
      "Trendy cocktail bar in the heart of the nightlife district. Modern design, loyal customer base. Fully licensed with all permits in order.",
    category: "bar",
    address: {
      real: {
        street: "Rruga Pjeter Bogdani, Nr 8",
        city: "Tirana",
        country: "Albania",
        coordinates: { lat: 41.3285, lng: 19.8195 },
      },
      public: {
        area: "City Center",
        city: "Tirana",
        country: "Albania",
        radiusKm: 0.5,
      },
    },
    realBusinessName: "The Speakeasy Lounge",
    askingPrice: 180000,
    annualRevenue: 220000,
    monthlyProfit: 6500,
    roi: 43,
    employeeCount: 6,
    yearsInOperation: 4,
    leaseTermsMonths: 36,
    images: ["/modern-cocktail-bar-interior-dark.jpg", "/bar-counter-bottles.jpg"],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-11-10"),
    viewCount: 156,
    inquiryCount: 8,
    promotionTier: "featured",
  },
  {
    id: "listing-3",
    agentId: "agent-2",
    agent: mockAgents[1],
    publicTitle: "Boutique Hotel - 20 Rooms",
    publicDescription:
      "Charming boutique hotel with sea views. Recently renovated with modern amenities. Strong booking rates throughout the year. Includes restaurant and spa facilities.",
    category: "hotel",
    address: {
      real: {
        street: "Rruga Mak Albanin, Nr 15",
        city: "Durrës",
        country: "Albania",
        coordinates: { lat: 41.3246, lng: 19.4563 },
      },
      public: {
        area: "Beachfront District",
        city: "Durrës",
        country: "Albania",
        radiusKm: 1.5,
      },
    },
    realBusinessName: "Hotel Adriatico",
    askingPrice: 1200000,
    annualRevenue: 650000,
    monthlyProfit: 25000,
    roi: 25,
    employeeCount: 18,
    yearsInOperation: 12,
    leaseTermsMonths: 120,
    images: [
      "/boutique-hotel-exterior-mediterranean.jpg",
      "/luxury-hotel-room-sea-view.jpg",
      "/elegant-hotel-lobby.png",
    ],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-08-15"),
    updatedAt: new Date("2024-11-20"),
    viewCount: 412,
    inquiryCount: 23,
    promotionTier: "standard",
  },
  {
    id: "listing-4",
    agentId: "agent-2",
    agent: mockAgents[1],
    publicTitle: "Tech Services Company",
    publicDescription:
      "Established IT services company with government and corporate contracts. Skilled team of developers and support staff. Recurring revenue model.",
    category: "technology",
    address: {
      real: {
        street: "Rruga Ibrahim Rugova, Nr 5",
        city: "Tirana",
        country: "Albania",
        coordinates: { lat: 41.3267, lng: 19.8201 },
      },
      public: {
        area: "Business District",
        city: "Tirana",
        country: "Albania",
        radiusKm: 2,
      },
    },
    realBusinessName: "AlbaTech Solutions",
    askingPrice: 450000,
    annualRevenue: 380000,
    monthlyProfit: 15000,
    roi: 40,
    employeeCount: 22,
    yearsInOperation: 7,
    images: ["/modern-office-space-technology.jpg", "/team-meeting-office.png"],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-07-20"),
    updatedAt: new Date("2024-11-18"),
    viewCount: 189,
    inquiryCount: 15,
    promotionTier: "standard",
  },
  {
    id: "listing-5",
    agentId: "agent-1",
    agent: mockAgents[0],
    publicTitle: "Premium Coffee Shop Chain",
    publicDescription:
      "3 locations in prime areas. Strong brand recognition. Established supply chain and trained staff. Turnkey operation.",
    category: "cafe",
    address: {
      real: {
        street: "Multiple Locations",
        city: "Tirana",
        country: "Albania",
      },
      public: {
        area: "Multiple Locations",
        city: "Tirana",
        country: "Albania",
        radiusKm: 5,
      },
    },
    realBusinessName: "Kafe Tirana",
    askingPrice: 280000,
    annualRevenue: 420000,
    monthlyProfit: 11000,
    roi: 47,
    employeeCount: 15,
    yearsInOperation: 5,
    leaseTermsMonths: 48,
    images: ["/modern-coffee-shop.png", "/barista-making-coffee.jpg"],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-10-10"),
    updatedAt: new Date("2024-11-22"),
    viewCount: 298,
    inquiryCount: 19,
    promotionTier: "standard",
  },
  {
    id: "listing-6",
    agentId: "agent-2",
    agent: mockAgents[1],
    publicTitle: "Retail Fashion Store",
    publicDescription:
      "Popular fashion retail store in shopping center. Exclusive brand partnerships. Strong social media presence and loyal customer base.",
    category: "retail",
    address: {
      real: {
        street: "TEG Shopping Center, Unit 45",
        city: "Tirana",
        country: "Albania",
        coordinates: { lat: 41.3156, lng: 19.8234 },
      },
      public: {
        area: "Shopping District",
        city: "Tirana",
        country: "Albania",
        radiusKm: 1,
      },
    },
    realBusinessName: "Moda Elegante",
    askingPrice: 95000,
    annualRevenue: 180000,
    monthlyProfit: 4500,
    roi: 57,
    employeeCount: 4,
    yearsInOperation: 3,
    leaseTermsMonths: 24,
    images: ["/fashion-retail-store-interior.jpg"],
    status: "active",
    isPhysicallyVerified: true,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-25"),
    viewCount: 87,
    inquiryCount: 5,
    promotionTier: "standard",
  },
]

export const mockContactLogs: ContactLog[] = [
  {
    id: "contact-1",
    listingId: "listing-1",
    listing: mockListings[0],
    buyerId: "buyer-1",
    buyer: mockBuyers[0],
    agentId: "agent-1",
    agent: mockAgents[0],
    contactMethod: "whatsapp",
    createdAt: new Date("2024-11-10"),
  },
  {
    id: "contact-2",
    listingId: "listing-3",
    listing: mockListings[2],
    buyerId: "buyer-1",
    buyer: mockBuyers[0],
    agentId: "agent-2",
    agent: mockAgents[1],
    contactMethod: "email",
    createdAt: new Date("2024-11-20"),
  },
]

// Helper functions
export function formatNumber(num: number): string {
  return new Intl.NumberFormat("en-US").format(num)
}
